name: "dbt_demo"
version: "1.0.0"
profile: "dbt_demo"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_demo:
    geo:
      +tags:
        - geo
      dws:
        dws_city:
          +materialized: table
      ads:
        dashboard_overview:
          +materialized: table
        dashboard_od:
          +materialized: table
        dashboard_provider:
          +materialized: table
    event:
      +materialized: table
      +tags:
        - event
