version: 2

sources:
  - name: demo
    schema: demo
    tables:
      - name: trips
        columns:
          - name: trip_id
            tests:
              - unique
              - not_null
          - name: provider_id
            tests:
              - accepted_values:
                  values: [1, 2, 3]

      - name: registers
        columns:
          - name: user_id
            tests:
              - unique
              - not_null
          - name: event_time
      - name: logins
        columns:
          - name: user_id
            tests:
              - relationships:
                  to: ref('registers')
                  field: user_id
          - name: event_time
      - name: transactions
        columns:
          - name: user_id
            tests:
              - relationships:
                  to: ref('registers')
                  field: user_id
          - name: event_time
          - name: amount

